### ISSUE TITLE
improve design on blockbuilder.org/search page

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/blockbuilder-search#12]

**Comment by dezein** [comment]
i'll organize my feedback into 2 categories, aesthetic and functional

**Comment by dezein** [comment]
aesthetic
- increase the margin in between the 'block-description' and 'block user' - i typically test margins by units of 5 or 10, so see how it looks w/ a 10px margin to give the description a bit of breathing room, and if it looks off, knock it down to a 5px margin. that way descending characters won't overlap the characters of the subsequent lines
- instead of going full black for the text, try using a dark gray font color like #444444, dark grays are less harsh against the full-white stroke applied to the block title elements; good call using the white outline to make sure the title text is visible above all preview images tho

- i think the visualization preview image with the zoom on hover is a nice touch to provide insital context for people searching through blocks

**Comment by dezein** [comment]
utility
- i would add an icon to the filter drop down lists to quickly convey to users that the items they select will be applied as filters to the content displayed; the blocks. this could be a + icon or something else
-  as of right now the filter inputs look like text fields, which threw me off when i clicked them and they functioned like a dropdown menu, perhaps style them like a dropdown menu so their affordance is conveyed to the user
- the content in the input filter dropdowns could also use some kind of icon to convey it's affordance; maybe a + by each list item?

**Comment by micahstubbs** [comment]
👍

**Comment by micahstubbs** [comment]
picking this up 😄
